//posts
export const UPDATE_POSTS ='UPDATE_POSTS';
//login
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAILED ='LOGIN_FAILED';
//if login is succes
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOG_OUT ='LOG_OUT';

//signup
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
//
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
//
export const EDIT_USER_SUCCESSFUL ='EDIT_USER_SUCCESSFUL';
export const EDIT_USER_FAIL ='EDIT_USER_FAIL';
//
export const USER_PROFILE_SUCCESS ='USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL ='USER_PROFILE_FAIL';
export const FETCH_USER_PROFILE='FETCH_USER_PROFILE';
//
export const FETCH_FRIEND_SUCCESS = 'FETCH_FRIEND_SUCCESS';
export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';
//
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
//
export const UPDATE_POST_LIKE='UPDATE_POST_LIKE';
//
export const FETCH_SEARCH_RESULTS_SUCCESS='FETCH_SEARCH_RESULTS_SUCCESS';